### ISSUE TITLE
sometimes it won't close result window when clicking `find all in current doc`, `find all in all opened doc` button

### ISSUE THREAD

**Issue by jackusay** [jackusay/cuda_find_in_filesX#10]
weird, it needs to click twice

**Comment by jackusay** [comment]
currently, the issue is gone.

may be it is affected by cudatext cache.

**Comment by veksha** [comment]
Find in Files 4 is bugged, and code is hard. I have hope that you will fix it :D

**Comment by jackusay** [comment]
may be I solve the problem.
```py
m.ag.hide() #hide find window #will this cause problem???
m.ag.update()
```
use this two at the same time may solve the problem.

Then I can finish this project.

---

original I used FiF3 but Encountered a bug, Alexey-T suggested me use FiF4....

If I encounter a bug I can't solve,

my plan B is use simple plugin: cudatext --> grep_gui(win only) --> cudatext

my plan C is write from scratch, I only need simple grep-like function with few buttons. may be this is faster than debug FiF....
It provides too many function, the code are too complicated.
