### ISSUE TITLE
close bottom panel when exiting cudatext

### ISSUE THREAD

**Issue by jackusay** [jackusay/cuda_find_in_filesX#13]
currently, user uses FiFX, then close cudatext. next time it will show a opened empty bottom panel.

**Comment by jackusay** [comment]
install.inf:
```ini
[item500]
section=events
events=on_exit
```

```py
bpanel = Bpanel() #ok
class Command:
    def on_exit(self, ed_self):               return bpanel.close_console()
    ...

class Bpanel:
    def close_console(self):
        app.app_proc(app.PROC_SHOW_BOTTOMPANEL_SET, False)
````

this will close bottom panel when exiting cudatext, but **still** open bottom panel when next time user open cudatext!

**Comment by jackusay** [comment]
```py
app.dlg_proc(self.bottom_ed, app.DLG_FREE) #uselss
```
```py
ed.cmd(cmds.cmd_HideBottomPanel) #useless
```

**Comment by jackusay** [comment]
try workaround - close panel when opening cudatext

> on_start(self, ed_self): Called once on program start. Called early, before applying config files. ed_self is None.

```
TypeError: an integer is required (got type Editor)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xxx\Downloads\app note\cudatext-windows-i386-1.188.0.0\py\cuda_find_in_filesX\cd_fif4.py", line 380, in on_start
    def on_start(self, ed_self):               return bpanel.exit_cudatext()
  File "C:\Users\xxx\Downloads\app note\cudatext-windows-i386-1.188.0.0\py\cuda_find_in_filesX\bottom_panel.py", line 229, in exit_cudatext
    app.dlg_proc(self.bottom_ed, app.DLG_HIDE)
  File "C:\Users\xxx\Downloads\app note\cudatext-windows-i386-1.188.0.0\py\cudatext.py", line 1282, in dlg_proc
    res = ct.dlg_proc(id_dialog, id_action, to_str(prop), index, index2, name)
SystemError: <built-in function dlg_proc> returned a result with an error set
ERROR: Exception in CudaText for on_start: SystemError: <built-in function dlg_proc> returned a result with an error set
```

**Comment by jackusay** [comment]
try workaround - close panel when opening cudatext

**Comment by jackusay** [comment]
maybe this is a feature

**Comment by veksha** [comment]
workaround:
ed.cmd(cmd_ShowPanelConsole)
ed.cmd(cmds.cmd_HideBottomPanel)

**Comment by veksha** [comment]
you need to create bottom panel by not using [bottombar1] in .inf

**Comment by veksha** [comment]
@Alexey-T , [bottombar1] in `.inf` always auto-activates on plugin load? maybe this is bad?

**Comment by Alexey-T** [comment]
@veksha This section just shows the sidebar icon . It must not activate the panel if panel was not activated on app closing.

**Comment by veksha** [comment]
you are right. so maybe on_exit event is happening to late (after state of bottom panel has been already recorded to session)

**Comment by Alexey-T** [comment]
what are steps with FIF4 plugin, to see the appearing of bottom panel?

**Comment by veksha** [comment]
read 1st two messages.

**Comment by Alexey-T** [comment]
Ah, it is new forked plugin FIFX. 
yes, on_exit may fire too late. plugin maybe need to find the bottom-panel before on_exit.

**Comment by veksha** [comment]
in `TfmMain.FormClose` can we swap like this:
DoPyEvent(nil, cEventOnExit, []);
DoOps_SaveHistory(UiOps.SaveModifiedTabsOnClose);

**Comment by Alexey-T** [comment]
Done as suggested.
